[#109] cash 거스름돈 controller 구현
ued123/modeling pull request #111
Opened 2022-11-06 12:32 UTC by ued123

우선 controller 정의하고 테스트 코드 작성하였습니다.

1. Cash가 0원일때 발생시킬 CashEmptyException 커스텀 에러를 생성, handler추가, Error 메시지 추가
2. Controller 생성 , 테스트 코드 200,404,500 케이스 테스트
3. service단은 인터페이스만 생성 하였음

2022-11-07 09:36 UTC, sangholim commented
@ued123 
- 상속을 통해 예외 클래스를 만든 경우면,  `ExceptionTranslator` 클래스에서 정의시 상속 주체 클래스를 통하여 함수 정하는게 관리하는데 도움이 될것 같습니다.
- 추가로 에러 응답 관련 소스 일부 리팩토링 했는데 검토 요청 드립니다. 🙏

2022-11-07 09:39 UTC, sangholim requested changes

2022-11-07 09:39 UTC, sangholim commented on cash-api/src/main/java/com/example/ExceptionTranslator.java
> +
```java
    /**
     * ResponseStatusException 및 구현힌 클래스인 경우,
     * 예외 발생시 ResponseEntity 생성 로직
     * @param exception @ModelAttribute 나 @RequestBody 유효성 검사 실패시 발생하는 예외
     */
    @ExceptionHandler(ResponseStatusException.class)
    public ResponseEntity<ErrorBody> responseStatusException(ResponseStatusException exception){
        return ResponseEntity
                .status(exception.getStatus())
                .body(ErrorBody.of(exception));
    }
```

2022-11-07 09:39 UTC, sangholim commented on cash-api/src/main/java/com/example/error/ErrorBody.java
> +    /**
```java
    /**
     * 에러 바디 객체 생성 함수 (ResponseStatusException)
     */
    public static ErrorBody of(ResponseStatusException exception) {
        return new ErrorBody(exception.getReason());
    }
```

2022-11-07 09:39 UTC, sangholim commented on cash-api/src/main/java/com/example/error/exception/CashEmptyException.java
> +    }
```java

    public CashEmptyException(HttpStatus status) {
        super(status, ErrorMessage.CASH_EMPTY);
    }

```

2022-11-07 09:43 UTC, sangholim commented on cash-api/src/main/java/com/example/error/ErrorBody.java
> +
```java
    /**
     * 에러 바디 객체 생성 함수 (ResponseStatusException)
     */
    public static ErrorBody of(ResponseStatusException exception) {
        return new ErrorBody(exception.getReason());
    }
```

2022-11-08 12:22 UTC, ued123 commented on cash-api/src/main/java/com/example/error/ErrorBody.java
> +
이부분은 설계 했던 #106 하고 error body값이 다른거 같아서요. 바꿔야 할까요?

2022-11-08 13:03 UTC, sangholim approved these changes

2022-11-09 10:47 UTC, merged