### 공통 모듈 생성,mongodb docker 구성
ued123/modeling pull request #13
Opened 2022-06-13 13:31 UTC by ued123

### 공통 모듈 생성
> - core 모듈 분리 공통 모듈 관리 할 예정

### api 모듈 기본 구성
> - 기본 구조 구성 , 추후 구현 예정

### mongodb dockerfile, build.sh 구성
> - mongodb dockerfile 로 설정과 초기화 데이터 구성
> - build.sh 구성하여 이미지 로딩 까지

### README.md 실행 방법 업데이트
> - 일단 api 틀만 작성했습니다. mongodb를 dockerfile로 생성하는 거랑 공통 모듈을 만들었습니다.

2022-06-14 00:46 UTC, sangholim requested changes
@ued123 
음료 전시는 패키지 하나 생성하셔서 관리하시는게 좋을거 같습니다

2022-06-14 00:46 UTC, sangholim commented on api/src/main/java/com/example/drink/dto/DisplayDrinkDto.java
> +public class DisplayDrinkDto {
DisplayDrinkDto -> DrinkDisplayDto

2022-06-14 21:48 UTC, sangholim commented
@ued123 
전시 도메인은 음료 도메인에 의존해야 하는데..
음료 도메인이 메인 프로젝트로 가져가는게 낫지 않을까요??

2022-06-14 22:29 UTC, ued123 commented
@sangholim 
제가 해당 부분에서 고민한점이 루트 프로젝트 이름이 drink로 되어있어가지고 이렇게 만들었거든요
<img width="255" alt="image" src="https://user-images.githubusercontent.com/32861341/173699867-d9f6833b-cfc9-4561-8f1a-c93717292522.png">
<img width="341" alt="image" src="https://user-images.githubusercontent.com/32861341/173699665-46b5411f-9b06-450a-8506-478a56b21664.png">

루트 프로젝트는 무시하고 가야하는건지 그걸 잘 모르겠슴다 ..

2022-06-26 04:41 UTC, ued123 commented
- issue #15 에 따른 새롭게 구현해야 하므로 close

2022-06-26 04:41 UTC, closed without merging