[#131] 음료수 구매 rest controller 생성
ued123/modeling pull request #133
Opened 2022-11-22 12:29 UTC by ued123

## comment
### 음료수 구매 rest controller 생성
1. ResponseEntity 활용. 헤더 값만 응답 할 수 있도록 정의함.
2. 컨트롤러 kotest 작성(validation error, server error ,204 정상케이스)

2022-11-23 08:10 UTC, sangholim requested changes

2022-11-23 08:10 UTC, sangholim commented on purchase-api/src/main/java/com/example/purchase/controller/PurchaseController.java
> +        return purchaseService.purchaseDrink(purchaseDrinkPayLoad);
Reponse Class 정의를 하시지 않으셔도 됩니다.

2022-11-23 08:10 UTC, sangholim commented on purchase-api/src/main/java/com/example/purchase/controller/PurchaseController.java
> +    @PostMapping(value = "/drink",consumes = MediaType.APPLICATION_JSON_VALUE)
@PostMapping(value = "/drink",consumes = MediaType.APPLICATION_JSON_VALUE)
@ResponseStatus(HttpStatus.NO_CONTENT)

2022-11-23 08:10 UTC, sangholim commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseService.java
> +    ResponseEntity<String> purchaseDrink(PurchaseDrinkPayLoad purchaseDrinkPayLoad);
Serice 단위에서 ResponseEntity를 정의하지 않습니다.

2022-11-23 08:10 UTC, sangholim commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseServiceImpl.java
> +    }
Serice 단위에서 ResponseEntity를 정의하지 않습니다.

2022-11-23 13:49 UTC, ued123 commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseServiceImpl.java
> +    }
제가 `ResponseEntity`를 서비스 단에서 사용한 이유는 `View` dto를 서비스단으로 부터 건네받아 controller 응답으로 사용해서 헷갈린 부분이 있었던 것 같습니다.

dto는 각 layer간에 데이터 전송에 쓰일수 있으니 서비스 단에서도 사용 할 수 있으나 `ResponseEntity`는 사용하면 안되겠네요.
수정 하도록 하겠습니다.

2022-11-23 14:04 UTC, ued123 commented
1. 음료수 구매 서비스는 단위 테스트를 위해서 int 형으로 리턴값을 정의했습니다.
2. controller 단에서 어노테이션을 활용한 리턴

2022-11-23 14:05 UTC, sangholim commented
@ued123 
- 만약 응답값이 없는 경우면.. mongo testcontainer 통한 통합 테스트가 필요한 상황이겠군여... 어떻게 생각하시는지??

2022-11-26 00:24 UTC, sangholim requested changes

2022-11-26 00:24 UTC, sangholim commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseService.java
> +    int purchaseDrink(PurchaseDrinkPayLoad purchaseDrinkPayLoad);
@ued123 
- 저희가 논의 하기로는 자판기에서는 음료를 선택하면 반드시 한개의 음료가 나오는 구조기 떄문에, 수량을 응답을 주는건 의미가 없다고 봅니다.
- 반환 값 int는 선언하신 이유가 궁급합니다

2022-11-26 00:24 UTC, sangholim commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseServiceImpl.java
> +        return 0;
@ued123 
- 저희가 논의 하기로는 자판기에서는 음료를 선택하면 반드시 한개의 음료가 나오는 구조기 떄문에, 수량을 응답을 주는건 의미가 없다고 봅니다.
- 반환 값 int는 선언하신 이유가 궁급합니다

2022-11-26 00:38 UTC, ued123 commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseService.java
> +    int purchaseDrink(PurchaseDrinkPayLoad purchaseDrinkPayLoad);
수량을 응답으로 주려고 의도한 리턴값은 아닙니다.
단위테스트나 해당 메서드가 정상적으로 실행되었는지 검증하기 위해서 int값으로 선언을 했습니다.

2022-11-26 00:42 UTC, sangholim commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseService.java
> +    int purchaseDrink(PurchaseDrinkPayLoad purchaseDrinkPayLoad);
- 보통 도메인내에서 처리하는 서비스인 경우, 반환값을 해당 도메인을 주는 경우가 많으니깐,
- 이거 병합 후에 `Purchase` 도메인으로 바꾸는게 어덜까요
- 결과값을 더 정확히 확인할수 잇을거 같습니다

2022-11-26 00:47 UTC, ued123 commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseService.java
> +    int purchaseDrink(PurchaseDrinkPayLoad purchaseDrinkPayLoad);
옙.. 사실 리턴값이 에매하긴 한거 같아요. 왜나하면 서비스단이 구현되기전에 controller 단부터 일단 만들어 놓고 고민하려고보니 리턴값을 에매하게 정의하게 된거 같습니다.

일의 우선순위가 Controller, service 둘중 서비스단 먼저 보통 구현을 해야할지 잘모르겠네요. 이렇게 보면 서비스단먼저 만드는게 낫겠네요

2022-11-26 00:48 UTC, sangholim commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseService.java
> +    int purchaseDrink(PurchaseDrinkPayLoad purchaseDrinkPayLoad);
- 고럼 이부분은 병합하고
- 다음에는 엔티티 도메인 부터 만드는것부터 진행할수 있게 처리해야겟네용

2022-11-26 00:49 UTC, sangholim approved these changes

2022-11-26 00:51 UTC, ued123 commented on purchase-api/src/main/java/com/example/purchase/service/PurchaseService.java
> +    int purchaseDrink(PurchaseDrinkPayLoad purchaseDrinkPayLoad);
넵 그래야할거 같아요

2022-11-26 04:10 UTC, merged