### 몽고디비 연동
ued123/modeling pull request #2
Opened 2022-05-30 13:33 UTC by ued123

> - mongodb docker-compose.yml 작성
> - 더미데이터 init data json 작성
> - mongoTemplate, mongoClient 수동 빈 등록
> - test코드 작성. 현재는 커넥션 연결 상태만 확인. startSession

@skydrive888

2022-05-30 21:40 UTC, sangholim requested changes

2022-05-30 21:40 UTC, sangholim commented on src/main/java/com.example/config/AppConfig.java
> +        return new MongoTemplate(mongoClient(), "vending_machine");
databaase 이름 작성하실때 underScore 대신 hypen 으로 해주세요
vending-machine

2022-05-30 21:40 UTC, sangholim commented on src/test/java/com/example/config/AppConfigTest.java
> +        MongoDatabase mongoDatabase = mongoClient.getDatabase("vending_machine");
databaase 이름 작성하실때 underScore 대신 hypen 으로 해주세요
vending-machine

2022-05-30 21:42 UTC, sangholim commented
@ued123 
수고하셨습니다.. 일단 위의 부분만 수정하고 병합 부탁드리고,
테스트 코드는 test-container 기반으로 작성하면 좋을 것 같습니다.

2022-05-31 10:54 UTC, ued123 commented on src/test/java/com/example/config/AppConfigTest.java
> +        MongoDatabase mongoDatabase = mongoClient.getDatabase("vending_machine");
webhook테스트

2022-05-31 11:03 UTC, ued123 commented on src/test/java/com/example/config/AppConfigTest.java
> +        MongoDatabase mongoDatabase = mongoClient.getDatabase("vending_machine");
webhook테스트3

2022-06-01 04:26 UTC, merged