[#84] Display 도메인 유닛테스트 bdd 스타일로 변경
ued123/modeling pull request #89
Opened 2022-10-18 12:31 UTC by seungheoni

- repo,controller,service kotest 적용
- Kotest 전용 MongoDB Container 코드 추가 (DbExtension.kt)
- Kotest 프로젝트 설정 코드 추가 (KotestProjectConfig.kt)
- DisplayBuilder 추가
- 기존 junit 테스트 코드 삭제

2022-10-18 12:36 UTC, ued123 commented
## 이슈
전에 말씀하신대로 ControllerTest의 WebTestClient 사용한 테스트시 .isEqualTo()로 모킹한 mongo Object를 비교시 기존 mocking한 객체보다 결과 ObjectId가 1증가하는 문제가 있어서 expectBody로만 비교하였습니다.

2022-10-18 13:33 UTC, sangholim requested changes

2022-10-18 13:33 UTC, sangholim commented on drink-api/src/test/kotlin/com/example/display/service/DisplayServiceTest.kt
> +                result is List<Display>
`is`  kotlin 에서 클래스 타입 여부 확인하는 operator로 알고 있습니다.
kotest 에서 클래스 타입 여부를 체크하는  operator 로 바꿔주세요

2022-10-18 13:33 UTC, sangholim commented on drink-api/src/test/kotlin/com/example/display/repo/DisplayRepositoryTest.kt
> +                result is Display
`is`  kotlin 에서 클래스 타입 여부 확인하는 operator로 알고 있습니다.
kotest 에서 클래스 타입 여부를 체크하는  operator 로 바꿔주세요

2022-10-18 13:52 UTC, ued123 commented on drink-api/src/test/kotlin/com/example/display/service/DisplayServiceTest.kt
> +                result is List<Display>
영어 문법으로 결과를 확인하는 느낌으로 지원하는 줄 알고 썼네요 착각했습니다. 죄송함다. 수정하도록 하겠습니다.

2022-10-18 13:53 UTC, sangholim commented on drink-api/src/test/kotlin/com/example/display/service/DisplayServiceTest.kt
> +                result is List<Display>
kotest 문법 보시고 한번 적용해보세용

2022-10-18 14:20 UTC, ued123 commented
`shouldBeInstanceOf<List<Display>>() ` 가 List 원소 타입까지 확인 해주진 않아서 `assertSoftly` 를 사용하여 원소까지 더 검증하는 로직을 넣었습니다.

2022-10-19 11:59 UTC, sangholim requested changes

2022-10-19 11:59 UTC, sangholim commented on drink-api/src/test/kotlin/com/example/display/service/DisplayServiceTest.kt
> +    }
@ued123 
- stub 의 기대값을 변수로 선언하고, 결과값 검증시 비교하는 방법은 어떨까요?

```kotlin

    Given("display와 drink의 룩업된 전체 리스트 조회 서비스") {
        When("displayServiceImpl의 displayDrinks 조회시") {
            val expected = listOf(Display.of(1,ObjectId.get()))
            every {
                displayRepository.findWithDrink();
            } returns expected
            val result = displayServiceImpl.displayDrinks
            Then("drink 컬렉션과 룩업된 Display 객체 리스트를 반환한다.") {
                result.shouldBeSameInstanceAs(expected)
            }
        }
    }
```

2022-10-19 12:07 UTC, ued123 commented on drink-api/src/test/kotlin/com/example/display/service/DisplayServiceTest.kt
> +    }
@sangholim
아하 이런 방법이 있군요. 검증이 깔끔한거 같습니다. 한번 적용 해보겠습니다.

2022-10-19 12:22 UTC, ued123 commented
확실히 `assertSoftly` 다중 검증 로직보다 `shouldBeSameInstanceAs` 사용이 깔끔한거 같습니다. 변경 완료.

2022-10-20 11:18 UTC, merged