Drink bdd 스타일 kotest 적용
ued123/modeling pull request #90
Opened 2022-10-20 12:00 UTC by ued123

drink는 repository만 존재하고 기타 로직은 없어서 repository만 적용했습니다.

2022-10-20 13:14 UTC, sangholim commented
@ued123 
- 소스에 `;` 끝나는 부분 제거 요청 드립니다.

2022-10-23 09:38 UTC, sangholim requested changes

2022-10-23 09:38 UTC, sangholim commented on drink-api/src/test/kotlin/com/example/drink/repo/DrinkRepositoryTest.kt
> +        }
```kotlin

    Given("drink repository 삭제 테스트") {
        val drink = Drink.of("콜라", 1000, 10)
            .let(drinkRepository::save)
        When("콜라(drink) 상품 삭제하면") {
            val result = drinkRepository.delete(drink)
            Then("성공시 void를 반환한다.") {
                result shouldBe kotlin.Unit
            }
        }
    }

    Given("drink repository 조회 테스트") {
        val drink = Drink.of("콜라", 1000, 10)
            .let(drinkRepository::save)
        When("콜라(drink) 상품 조회하면") {
            val result = drinkRepository.findById(drink.id)
            Then("아까 저장한 콜라(drink)를 반환한다.") {
                result.get().id shouldBe drink.id
            }
        }
    }
```

2022-10-23 09:49 UTC, ued123 commented on drink-api/src/test/kotlin/com/example/drink/repo/DrinkRepositoryTest.kt
> +        }
이렇게 변경하도록 하겠습니다!

2022-10-26 07:26 UTC, sangholim approved these changes

2022-10-26 08:18 UTC, merged